### ISSUE TITLE
Add unit tests and continuous integration 

### ISSUE THREAD

**Issue by tsalo** [tsalo/gclda#3]
I've already added the test files, but they're currently empty.

**Comment by tsalo** [comment]
First tests added in c2e43058880c516ce1a915063eb5901e97f4f0f4. I also took the first 10 articles in Neurosynth as a test dataset.

**Comment by emdupre** [comment]
Initial coverage reports are right at 50%-- looking good! 👍

**Comment by tsalo** [comment]
Adding a test that actually runs a model will improve coverage significantly. I also need to make one that prints model parameters to files (and then cleans them up).

For dataset, it's mostly about the display functions. Not sure how to evaluate those.

Lastly, is there a way to ignore `due.py`?

**Comment by tsalo** [comment]
Still not sure how to ignore `due.py`, but after adding the other tests we're now up to 93%!

**Comment by emdupre** [comment]
Ignoring `due.py` might look something like [this](https://github.com/coveralls-clients/coveralls-python#tips-for-coveragerc-config)? Haven't tested it yet, though....
